### PR TITLE
Update reqwest dependency version to 0.9

### PR DESCRIPTION
**Pull request by braincow**
Reqwest 0.8 still has a dependency to old OpenSSL 0.9 which is not available in modern systems. Simple fix is to update Reqwest dependency to 0.9.

### CODE REVIEW

**Comment by ryanmcgrath** [comment]
Yo, I'm sympathetic to open source feeling like a thankless job... but this needs to be merged, there's multiple pull requests open trying to fix the issue.

**Comment by anthonyray** [comment]
Yo ! I think you can safely merge this P.R and perform a release ;) !

**Comment by gifnksm** [comment]
I'm sorry for being late. reqwest upgraded to 0.10 by #39.

**Comment by ryanmcgrath** [comment]
You rock! Thank you!

**Pull request closed without merging**
